### ISSUE TITLE
AP scan not working 

### ISSUE THREAD

**Issue by shadowe1ite** [DX4GREY/AirHack-Project#1]
I enabled monitor mode and selected the interface and started scan . But access points are not showing. Anyways to debug ?

**Comment by DX4GREY** [comment]
Use this version  <a href="https://github.com/DX4GREY/AirHack-Project/releases/tag/1.1.0">1.1.0</a> in scanner page, click fix interface

**Comment by shadowe1ite** [comment]
Still the same
